[phases.setup]
nixPkgs = ["php83", "php83Extensions.pdo", "php83Extensions.pdo_sqlite", "php83Extensions.mbstring", "php83Extensions.tokenizer", "php83Extensions.xml", "php83Extensions.ctype", "php83Extensions.bcmath", "php83Extensions.curl", "php83Extensions.fileinfo", "php83Extensions.openssl", "php83Extensions.zip", "php83Extensions.intl", "sqlite", "nodejs_20", "npm-10_x", "composer"]

[phases.install]
cmds = [
  "composer install --no-dev --optimize-autoloader --no-interaction",
  "npm ci",
  "npm run build"
]

[phases.build]
cmds = [
  "php artisan config:cache",
  "php artisan route:cache",
  "php artisan view:cache",
  "php artisan event:cache"
]

[start]
cmd = "php artisan migrate --force --seed && php artisan serve --host=0.0.0.0 --port=$PORT"
